
POST http://localhost:8080/api/benutzer
Content-Type: application/json

{
  "vollname":  "Joghurta Biffel",
  "loginname": "jogi",
  "passwort":  "taucha",
  "nutzungsbedingungenok": "true"
}

###

GET http://localhost:8080/api/benutzer/jogi

###

POST http://localhost:8080/api/braten?loginname=jogi
Content-Type: application/json

{
  "abholort":    "Am Zipfel 1, 12345 Vollradisroda",
  "haltbarbis":  "2022-11-17",
  "beschreibung":"Super leckerer Bratwurstbraten",
  "vgrad": 25
}

###
# Alle Braten abrufen
GET http://localhost:8080/api/braten/


### 
# ID ggf. anpassen

GET http://localhost:8080/api/braten/17

